{{- if and .Values.rbac.enabled .Values.rbac.namespaced }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "microservice-achievements.fullname" . }}
  labels:
    {{- include "microservice-achievements.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "microservice-achievements.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "microservice-achievements.serviceAccountName" . }}
    namespace: {{ template "microservice-achievements.namespace" . }}
{{- end -}}
